trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    publishJUnitResults: true
- task: AzureAppServiceManage@0
  inputs:
    Action: 'Start Azure App Service'
    WebAppName: 'my-app-service'
    ResourceGroupName: 'my-resource-group'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    publishJUnitResults: true
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'Regression Tests'
